spring.application.name=auth_server
# Datasource
spring.datasource.url=jdbc:postgresql://172.17.0.2:5432/postgres?currentSchema=oauth
spring.datasource.username=postgres
spring.datasource.password=myNewSecurePass123
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
spring.jpa.properties.hibernate.default_schema=oauth
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#tomcat thread
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=20
#connection pool
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout=30000
#path root
path.root.oauth2=/api/v1/
jwt.secret=my-super-secret-key-which-is-long-enough
#session after login success
server.servlet.session.timeout=30m
logging.file.name=logs/app.log
# Log level
logging.level.root=INFO
logging.level.com.authserver=DEBUG